@extends('layouts.auth')

@section('title', 'Forgot Password | Elevanix')

@section('content')
<div class="auth-split">
    <section class="auth-visual" aria-label="Password reset help">
        <a href="{{ route('home') }}" class="text-decoration-none"><x-brand-logo tone="light" /></a>
        <span class="portal-label">Password Recovery</span>
        <h1>Recover access securely.</h1>
        <p>Enter your account email and Elevanix will send a password reset link through the configured mail service.</p>
        <div class="auth-features">
            <x-auth.feature-item icon="fa-solid fa-lock" title="Secure Reset">Reset links are generated by Laravel's password broker.</x-auth.feature-item>
            <x-auth.feature-item icon="fa-solid fa-envelope" title="Email Delivery">Messages are sent to the registered account email.</x-auth.feature-item>
        </div>
        <small>&copy; {{ date('Y') }} Elevanix</small>
    </section>

    <section class="auth-form-panel">
        <div class="mobile-auth-brand"><a href="{{ route('home') }}" class="text-decoration-none"><x-brand-logo /></a></div>
        <div class="auth-card">
            <span class="form-badge">Account Recovery</span>
            <h2>Forgot your password?</h2>
            <p>Enter your email address and we will send a reset link if the account exists.</p>

            @if (session('status'))
                <div class="alert alert-success" role="status">{{ session('status') }}</div>
            @endif

            <form method="POST" action="{{ route('password.email') }}" data-loading-form>
                @csrf
                <div class="mb-4">
                    @include('partials.input', ['name' => 'email', 'label' => 'Email Address', 'type' => 'email', 'icon' => 'fa-regular fa-envelope'])
                </div>
                <button class="btn btn-primary w-100" type="submit" data-loading-text="Sending...">
                    <i class="fa-solid fa-paper-plane" aria-hidden="true"></i>
                    Send Reset Link
                </button>
            </form>
            <p class="auth-switch"><a href="{{ route('login') }}">Back to sign in</a></p>
        </div>
    </section>
</div>
@endsection
