<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Revenue Overview</title>
    <style>
        body { color: #475569; font-family: DejaVu Sans, sans-serif; font-size: 10px; }
        h1 { margin: 0 0 4px; color: #0F172A; font-size: 22px; }
        h2 { margin: 18px 0 8px; color: #1E293B; font-size: 14px; }
        .meta { margin-bottom: 14px; color: #64748B; line-height: 1.5; }
        .summary { width: 100%; margin-bottom: 14px; border-collapse: collapse; }
        .summary td { border: 1px solid #DBEAFE; padding: 8px; }
        .summary strong { display: block; color: #0F172A; font-size: 13px; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #EFF6FF; color: #1E293B; font-weight: bold; text-align: left; }
        th, td { border: 1px solid #DBEAFE; padding: 6px; vertical-align: top; }
        tr:nth-child(even) td { background: #F8FAFC; }
        .footer { margin-top: 18px; color: #64748B; font-size: 9px; text-align: center; }
    </style>
</head>
<body>
    <h1>Elevanix Revenue Overview</h1>
    <div class="meta">
        Generated: {{ $generatedAt->format('Y-m-d H:i') }}<br>
        Generated by: {{ $generatedBy }}<br>
        Revenue rule: only verified, received and paid subscription payments count as recognized platform revenue.
        @if($filters)
            <br>Filters:
            @foreach($filters as $label => $value)
                {{ $label }}={{ $value }}@if(! $loop->last), @endif
            @endforeach
        @endif
    </div>

    <table class="summary">
        <tr>
            <td>Total Platform Revenue<strong>{{ $currency }} {{ number_format($summary['total'], 2) }}</strong></td>
            <td>Revenue This Month<strong>{{ $currency }} {{ number_format($summary['month'], 2) }}</strong></td>
            <td>Revenue This Year<strong>{{ $currency }} {{ number_format($summary['year'], 2) }}</strong></td>
            <td>Pending Payments<strong>{{ $currency }} {{ number_format($summary['pending'], 2) }}</strong></td>
        </tr>
        <tr>
            <td>Verified Payments<strong>{{ $summary['verified_count'] }}</strong></td>
            <td>Refunded Payments<strong>{{ $summary['refunded_count'] }}</strong></td>
            <td>Active Subscriptions<strong>{{ $summary['active_subscriptions'] }}</strong></td>
            <td>Average Revenue / Company<strong>{{ $currency }} {{ number_format($summary['average_company'], 2) }}</strong></td>
        </tr>
    </table>

    <h2>Subscription Payment Transactions</h2>
    <table>
        <thead>
            <tr>
                <th>Reference</th>
                <th>Company</th>
                <th>Plan</th>
                <th>Amount</th>
                <th>Method</th>
                <th>Status</th>
                <th>Revenue Date</th>
                <th>Verified By</th>
            </tr>
        </thead>
        <tbody>
            @forelse($payments as $payment)
                <tr>
                    <td>{{ $payment->transaction_reference ?? 'Payment #'.$payment->id }}</td>
                    <td>{{ $payment->company?->name ?? '-' }}</td>
                    <td>{{ $payment->subscriptionPlan?->name ?? '-' }}</td>
                    <td>{{ $currency }} {{ number_format((float) $payment->amount, 2) }}</td>
                    <td>{{ str_replace('_', ' ', $payment->method) }}</td>
                    <td>{{ str_replace('_', ' ', ucfirst($payment->status)) }}</td>
                    <td>{{ ($payment->verified_at ?? $payment->paid_at ?? $payment->created_at)?->format('Y-m-d') }}</td>
                    <td>{{ $payment->verifier?->name ?? '-' }}</td>
                </tr>
            @empty
                <tr><td colspan="8">No revenue records match the selected filters.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">Elevanix Smart Software Company Management System</div>
</body>
</html>
