@extends('layouts.app')

@section('title', 'Projects - Elevanix')

@section('content')
@include('partials.page-header', ['eyebrow' => 'Company Admin', 'title' => 'Projects', 'description' => 'Create, assign, track and complete company projects.', 'actions' => new \Illuminate\Support\HtmlString('<a class="btn btn-primary" href="'.route('company-admin.projects.create').'"><i class="fa-solid fa-plus"></i>Create project</a>')])
<section class="content-card">
    <form class="row g-2 mb-3"><div class="col-md-4"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Search projects"></div><div class="col-md-3"><select class="form-select" name="status"><option value="">All statuses</option>@foreach(['planning','pending','approved','active','in_progress','on_hold','testing','completed','cancelled'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ str_replace('_',' ',ucfirst($status)) }}</option>@endforeach</select></div><div class="col-md-3"><select class="form-select" name="client_id"><option value="">All clients</option>@foreach($clients as $client)<option value="{{ $client->id }}" @selected(request('client_id')==$client->id)>{{ $client->name }}</option>@endforeach</select></div><div class="col-md-2"><button class="btn btn-outline-primary w-100" type="submit"><i class="fa-solid fa-filter"></i>Filter</button></div></form>
    <div class="table-responsive"><table class="table align-middle"><thead><tr><th>Project</th><th>Client</th><th>Progress</th><th>Tasks</th><th>Due Date</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>@forelse($projects as $project)<tr><td>{{ $project->name }}<small>{{ ucfirst($project->priority ?? 'medium') }}</small></td><td>{{ $project->client?->name ?? 'Internal' }}</td><td><div class="progress"><div class="progress-bar" style="width: {{ $project->progress }}%"></div></div><small>{{ $project->progress }}%</small></td><td>{{ $project->tasks_count }}</td><td>{{ $project->due_date?->format('Y-m-d') ?? '-' }}</td><td>@include('partials.status-badge', ['status' => $project->status])</td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="{{ route('company-admin.projects.show', $project) }}"><i class="fa-solid fa-eye"></i></a><a class="btn btn-sm btn-outline-primary" href="{{ route('company-admin.projects.edit', $project) }}"><i class="fa-solid fa-pen"></i></a></td></tr>@empty<tr><td colspan="7" class="empty-cell">No projects found.</td></tr>@endforelse</tbody></table></div>
    {{ $projects->links() }}
</section>
@endsection
