@extends('layouts.app')

@section('title', 'Platform Users - Elevanix')

@section('content')
@include('partials.page-header', ['eyebrow' => 'Super Admin', 'title' => 'Platform Users', 'description' => 'View users across all companies without exposing passwords.'])
<section class="content-card">
    <form class="row g-3 mb-3" method="GET"><div class="col-md-3"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Search users"></div><div class="col-md-3"><select class="form-select" name="role"><option value="">All roles</option>@foreach($roles as $role)<option value="{{ $role }}" @selected(request('role') === $role)>{{ str_replace('_', ' ', ucfirst($role)) }}</option>@endforeach</select></div><div class="col-md-3"><select class="form-select" name="company"><option value="">All companies</option>@foreach($companies as $company)<option value="{{ $company->id }}" @selected(request('company') == $company->id)>{{ $company->name }}</option>@endforeach</select></div><div class="col-md-2"><select class="form-select" name="status"><option value="">All statuses</option>@foreach($statuses as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ ucfirst($status) }}</option>@endforeach</select></div><div class="col-md-1"><button class="btn btn-primary w-100" type="submit"><i class="fa-solid fa-filter"></i></button></div></form>
    <div class="table-responsive"><table class="table align-middle"><thead><tr><th>Name</th><th>Role</th><th>Company</th><th>Status</th><th>Last Login</th><th>Created</th><th></th></tr></thead><tbody>@forelse($users as $user)<tr><td>{{ $user->name }}<small>{{ $user->username }} - {{ $user->email }}</small></td><td>{{ str_replace('_', ' ', $user->role) }}</td><td>{{ $user->company?->name ?? 'Platform' }}</td><td>@include('partials.status-badge', ['status' => $user->status])</td><td>{{ $user->last_login_at?->diffForHumans() ?? 'Never' }}</td><td>{{ $user->created_at->format('M d, Y') }}</td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('super-admin.users.show', $user) }}"><i class="fa-regular fa-eye"></i> View</a></td></tr>@empty<tr><td colspan="7" class="empty-cell">@include('partials.empty-state', ['icon' => 'fa-users', 'title' => 'No users found', 'message' => 'Try changing your filters.'])</td></tr>@endforelse</tbody></table></div>{{ $users->links() }}
</section>
@endsection
