@extends('layouts.app')

@section('title', 'Payments - Elevanix')

@section('content')
@include('partials.page-header', ['eyebrow' => 'Company Admin', 'title' => 'Payments', 'description' => 'Manage client project payment requests and verification.', 'actions' => new \Illuminate\Support\HtmlString('<a class="btn btn-primary" href="'.route('company-admin.payments.create').'"><i class="fa-solid fa-plus"></i>Create payment</a>')])
<section class="content-card">
    <form class="row g-2 mb-3"><div class="col-md-4"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Search reference, invoice or client"></div><div class="col-md-3"><select class="form-select" name="status"><option value="">All statuses</option>@foreach(['pending','requested','proof_submitted','partially_paid','paid','rejected','refunded','received'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ str_replace('_',' ',ucfirst($status)) }}</option>@endforeach</select></div><div class="col-md-2"><button class="btn btn-outline-primary" type="submit"><i class="fa-solid fa-filter"></i>Filter</button></div></form>
    <div class="table-responsive"><table class="table align-middle"><thead><tr><th>Reference</th><th>Invoice</th><th>Client</th><th>Project</th><th>Amount</th><th>Method</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td>{{ $payment->transaction_reference ?? '#'.$payment->id }}</td><td>@if($payment->invoice)<a href="{{ route('company-admin.invoices.show', $payment->invoice) }}">{{ $payment->invoice->invoice_number }}</a>@else - @endif</td><td>{{ $payment->client?->name ?? '-' }}</td><td>{{ $payment->project?->name ?? '-' }}</td><td>{{ $currency }} {{ number_format($payment->amount, 2) }}</td><td>{{ str_replace('_',' ',ucfirst($payment->method)) }}</td><td>@include('partials.status-badge', ['status' => $payment->status])</td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="{{ route('company-admin.payments.show', $payment) }}" title="View payment"><i class="fa-solid fa-eye"></i></a><a class="btn btn-sm btn-outline-primary" href="{{ route('company-admin.payments.edit', $payment) }}" title="Edit payment"><i class="fa-solid fa-pen"></i></a></td></tr>@empty<tr><td colspan="8" class="empty-cell">No payments found.</td></tr>@endforelse</tbody></table></div>
    {{ $payments->links() }}
</section>
@endsection
