@extends('layouts.app')

@section('title', 'System Settings - Elevanix')

@section('content')
@include('partials.page-header', ['eyebrow' => 'Super Admin', 'title' => 'System Settings', 'description' => 'Safe platform-level settings only. Environment secrets are never exposed here.'])
@php
    $timezones = DateTimeZone::listIdentifiers();
    $dateFormats = ['Y-m-d', 'd/m/Y', 'm/d/Y', 'd M Y', 'M d, Y'];
    $currencies = ['USD', 'LKR', 'EUR', 'GBP', 'AUD', 'CAD', 'INR', 'SGD'];
@endphp

<section class="content-card">
    <form method="POST" action="{{ route('super-admin.settings.update') }}" class="row g-3" data-loading-form>
        @csrf
        @method('PUT')
        <div class="col-12"><div class="content-card-header"><div><h2>Platform Identity</h2><p>Names and support details shown across the SaaS platform.</p></div></div></div>
        <div class="col-md-4"><label class="form-label" for="platform_name">Platform name</label><input class="form-control @error('platform_name') is-invalid @enderror" id="platform_name" name="platform_name" value="{{ old('platform_name', $settings['platform_name']) }}" required>@error('platform_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-2"><label class="form-label" for="platform_abbreviation">Abbreviation</label><input class="form-control @error('platform_abbreviation') is-invalid @enderror" id="platform_abbreviation" name="platform_abbreviation" value="{{ old('platform_abbreviation', $settings['platform_abbreviation']) }}">@error('platform_abbreviation')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-3"><label class="form-label" for="support_email">Support email</label><input class="form-control @error('support_email') is-invalid @enderror" id="support_email" type="email" name="support_email" value="{{ old('support_email', $settings['support_email']) }}" required>@error('support_email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-3"><label class="form-label" for="support_phone">Support phone</label><input class="form-control @error('support_phone') is-invalid @enderror" id="support_phone" name="support_phone" value="{{ old('support_phone', $settings['support_phone']) }}">@error('support_phone')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label class="form-label" for="platform_address">Address</label><input class="form-control @error('platform_address') is-invalid @enderror" id="platform_address" name="platform_address" value="{{ old('platform_address', $settings['platform_address']) }}">@error('platform_address')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-3"><label class="form-label" for="timezone">Timezone</label><select class="form-select @error('timezone') is-invalid @enderror" id="timezone" name="timezone" required>@foreach($timezones as $timezone)<option value="{{ $timezone }}" @selected(old('timezone', $settings['timezone']) === $timezone)>{{ $timezone }}</option>@endforeach</select>@error('timezone')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-3"><label class="form-label" for="date_format">Date format</label><select class="form-select @error('date_format') is-invalid @enderror" id="date_format" name="date_format" required>@foreach($dateFormats as $format)<option value="{{ $format }}" @selected(old('date_format', $settings['date_format']) === $format)>{{ now()->format($format) }} ({{ $format }})</option>@endforeach</select>@error('date_format')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>

        <div class="col-12"><div class="content-card-header mt-3"><div><h2>Branding</h2><p>Stored asset paths and safe display color. Upload management is not part of this settings table.</p></div></div></div>
        <div class="col-md-3"><label class="form-label" for="platform_logo">Logo path</label><input class="form-control @error('platform_logo') is-invalid @enderror" id="platform_logo" name="platform_logo" value="{{ old('platform_logo', $settings['platform_logo']) }}">@error('platform_logo')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-3"><label class="form-label" for="favicon">Favicon path</label><input class="form-control @error('favicon') is-invalid @enderror" id="favicon" name="favicon" value="{{ old('favicon', $settings['favicon']) }}">@error('favicon')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-3"><label class="form-label" for="primary_color">Primary color</label><input class="form-control @error('primary_color') is-invalid @enderror" id="primary_color" type="color" name="primary_color" value="{{ old('primary_color', $settings['primary_color']) }}">@error('primary_color')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-3"><label class="form-label" for="login_background_image">Login background</label><input class="form-control @error('login_background_image') is-invalid @enderror" id="login_background_image" name="login_background_image" value="{{ old('login_background_image', $settings['login_background_image']) }}">@error('login_background_image')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>

        <div class="col-12"><div class="content-card-header mt-3"><div><h2>Registration and Subscription</h2><p>Controls backed by existing registration and subscription settings.</p></div></div></div>
        <div class="col-md-3 form-check ms-2"><input class="form-check-input" type="checkbox" id="registration_enabled" name="registration_enabled" value="1" @checked(old('registration_enabled', $settings['registration_enabled']))><label class="form-check-label" for="registration_enabled">Enable company registration</label></div>
        <div class="col-md-3 form-check"><input class="form-check-input" type="checkbox" id="company_approval_required" name="company_approval_required" value="1" @checked(old('company_approval_required', $settings['company_approval_required']))><label class="form-check-label" for="company_approval_required">Require approval</label></div>
        <div class="col-md-2"><label class="form-label" for="trial_duration_days">Trial days</label><input class="form-control @error('trial_duration_days') is-invalid @enderror" id="trial_duration_days" type="number" min="0" max="365" name="trial_duration_days" value="{{ old('trial_duration_days', $settings['trial_duration_days']) }}" required>@error('trial_duration_days')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-2"><label class="form-label" for="currency">Currency</label><select class="form-select @error('currency') is-invalid @enderror" id="currency" name="currency" required>@foreach($currencies as $currency)<option value="{{ $currency }}" @selected(old('currency', $settings['currency']) === $currency)>{{ $currency }}</option>@endforeach</select>@error('currency')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-2"><label class="form-label" for="subscription_reminder_days">Reminder days</label><input class="form-control @error('subscription_reminder_days') is-invalid @enderror" id="subscription_reminder_days" type="number" min="1" max="90" name="subscription_reminder_days" value="{{ old('subscription_reminder_days', $settings['subscription_reminder_days']) }}" required>@error('subscription_reminder_days')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-3 form-check ms-2"><input class="form-check-input" type="checkbox" id="allow_trial_plan" name="allow_trial_plan" value="1" @checked(old('allow_trial_plan', $settings['allow_trial_plan']))><label class="form-check-label" for="allow_trial_plan">Allow trial plan</label></div>
        <div class="col-md-3 form-check"><input class="form-check-input" type="checkbox" id="allow_plan_upgrade" name="allow_plan_upgrade" value="1" @checked(old('allow_plan_upgrade', $settings['allow_plan_upgrade']))><label class="form-check-label" for="allow_plan_upgrade">Allow plan upgrade</label></div>

        <div class="col-12"><div class="content-card-header mt-3"><div><h2>Mail Display</h2><p>Sender display values only. Mail passwords and transport secrets stay in environment configuration.</p></div></div></div>
        <div class="col-md-6"><label class="form-label" for="email_sender_name">Sender name</label><input class="form-control @error('email_sender_name') is-invalid @enderror" id="email_sender_name" name="email_sender_name" value="{{ old('email_sender_name', $settings['email_sender_name']) }}" required>@error('email_sender_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label class="form-label" for="email_sender_email">Sender email display</label><input class="form-control @error('email_sender_email') is-invalid @enderror" id="email_sender_email" type="email" name="email_sender_email" value="{{ old('email_sender_email', $settings['email_sender_email']) }}">@error('email_sender_email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12"><button class="btn btn-primary" type="submit" data-loading-text="Saving system settings..."><i class="fa-solid fa-floppy-disk"></i>Save Changes</button></div>
    </form>
</section>
@endsection
