@extends('layouts.app')

@section('title', 'Tasks - Elevanix')

@section('content')
@include('partials.page-header', ['eyebrow' => 'Company Admin', 'title' => 'Tasks', 'description' => 'Track assignments, priorities, due dates and overdue work.', 'actions' => new \Illuminate\Support\HtmlString('<a class="btn btn-primary" href="'.route('company-admin.tasks.create').'"><i class="fa-solid fa-plus"></i>Create task</a>')])
<section class="content-card">
    <form class="row g-2 mb-3"><div class="col-md-3"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Search tasks"></div><div class="col-md-2"><select class="form-select" name="status"><option value="">All statuses</option>@foreach(['todo','assigned','in_progress','paused','submitted','under_review','completed','cancelled'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ str_replace('_',' ',ucfirst($status)) }}</option>@endforeach</select></div><div class="col-md-2"><select class="form-select" name="priority"><option value="">All priorities</option>@foreach(['low','medium','high','urgent'] as $priority)<option value="{{ $priority }}" @selected(request('priority')===$priority)>{{ ucfirst($priority) }}</option>@endforeach</select></div><div class="col-md-2"><select class="form-select" name="project_id"><option value="">All projects</option>@foreach($projects as $project)<option value="{{ $project->id }}" @selected(request('project_id')==$project->id)>{{ $project->name }}</option>@endforeach</select></div><div class="col-md-2"><select class="form-select" name="assignee_id"><option value="">All employees</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected(request('assignee_id')==$employee->id)>{{ $employee->name }}</option>@endforeach</select></div><div class="col-md-1"><button class="btn btn-outline-primary w-100" type="submit"><i class="fa-solid fa-filter"></i></button></div></form>
    <div class="table-responsive"><table class="table align-middle"><thead><tr><th>Task</th><th>Project</th><th>Assignee</th><th>Priority</th><th>Due</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>@forelse($tasks as $task)<tr><td>{{ $task->title }}<small>{{ ucfirst($task->task_type ?? 'task') }}</small></td><td>{{ $task->project?->name }}</td><td>{{ $task->assignee?->name ?? 'Unassigned' }}</td><td>{{ ucfirst($task->priority) }}</td><td>{{ $task->due_date?->format('Y-m-d') ?? '-' }} @if($task->due_date && $task->due_date->isPast() && ! in_array($task->status, ['completed','cancelled']))<span class="status-badge status-danger ms-1"><span></span>Overdue</span>@endif</td><td>@include('partials.status-badge', ['status' => $task->status])</td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="{{ route('company-admin.tasks.show', $task) }}"><i class="fa-solid fa-eye"></i></a><a class="btn btn-sm btn-outline-primary" href="{{ route('company-admin.tasks.edit', $task) }}"><i class="fa-solid fa-pen"></i></a></td></tr>@empty<tr><td colspan="7" class="empty-cell">No tasks found.</td></tr>@endforelse</tbody></table></div>
    {{ $tasks->links() }}
</section>
@endsection
