<?php

namespace App\Http\Controllers\SuperAdmin;

use App\Http\Controllers\Controller;
use App\Models\AuditLog;
use App\Models\Company;
use App\Models\Payment;
use App\Models\Subscription;
use App\Models\SubscriptionPlan;
use App\Models\SystemSetting;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use Illuminate\View\View;
use Symfony\Component\HttpFoundation\StreamedResponse;

class RevenueController extends Controller
{
    private const RECOGNIZED_STATUSES = ['verified', 'received', 'paid'];
    private const PENDING_STATUSES = ['pending', 'submitted', 'proof_submitted', 'requested'];
    private const ALL_STATUSES = ['pending', 'submitted', 'proof_submitted', 'requested', 'verified', 'received', 'paid', 'rejected', 'failed', 'refunded'];

    public function index(Request $request): View
    {
        $filters = $this->filters($request);
        $allPayments = $this->filteredPaymentQuery($filters)
            ->with(['company', 'subscriptionPlan', 'verifier'])
            ->get();

        $payments = $this->filteredPaymentQuery($filters)
            ->with(['company', 'subscriptionPlan', 'verifier'])
            ->latest($this->revenueDateExpression())
            ->paginate(10)
            ->withQueryString();

        return view('super-admin.revenue.index', [
            'payments' => $payments,
            'companies' => Company::orderBy('name')->get(),
            'plans' => SubscriptionPlan::orderBy('name')->get(),
            'statuses' => self::ALL_STATUSES,
            'periods' => $this->periodOptions(),
            'filters' => $filters,
            'currency' => $this->currency(),
            'summary' => $this->summary($allPayments, $filters),
            'chartData' => $this->chartData($allPayments),
        ]);
    }

    public function exportCsv(Request $request): StreamedResponse
    {
        $filters = $this->filters($request);
        $filename = 'elevanix-revenue-overview-'.now()->format('Y-m-d').'.csv';

        $this->recordExportAudit($request, 'csv', $filters);

        return response()->streamDownload(function () use ($filters): void {
            $out = fopen('php://output', 'w');
            fputcsv($out, $this->safeCsvRow(['Elevanix Revenue Overview']));
            fputcsv($out, $this->safeCsvRow(['Generated At', now()->format('Y-m-d H:i')]));
            fputcsv($out, $this->safeCsvRow(['Generated By', auth()->user()?->name ?? 'System']));
            foreach ($this->activeFilters($filters) as $label => $value) {
                fputcsv($out, $this->safeCsvRow([$label, $value]));
            }
            fputcsv($out, []);
            fputcsv($out, $this->safeCsvRow(['Reference', 'Company', 'Subscription Plan', 'Amount', 'Method', 'Status', 'Revenue Date', 'Verified By']));

            $this->filteredPaymentQuery($filters)
                ->with(['company', 'subscriptionPlan', 'verifier'])
                ->latest($this->revenueDateExpression())
                ->chunk(200, function ($payments) use ($out): void {
                    foreach ($payments as $payment) {
                        fputcsv($out, $this->safeCsvRow($this->exportRow($payment)));
                    }
                });

            fclose($out);
        }, $filename, ['Content-Type' => 'text/csv; charset=UTF-8']);
    }

    public function exportPdf(Request $request)
    {
        $filters = $this->filters($request);
        $payments = $this->filteredPaymentQuery($filters)
            ->with(['company', 'subscriptionPlan', 'verifier'])
            ->latest($this->revenueDateExpression())
            ->limit(500)
            ->get();

        $this->recordExportAudit($request, 'pdf', $filters);

        return Pdf::loadView('super-admin.revenue.pdf', [
            'generatedAt' => now(),
            'generatedBy' => auth()->user()?->name ?? 'System',
            'filters' => $this->activeFilters($filters),
            'summary' => $this->summary($payments, $filters),
            'payments' => $payments,
            'currency' => $this->currency(),
        ])->setPaper('a4', 'landscape')
            ->download('elevanix-revenue-overview-'.now()->format('Y-m-d').'.pdf');
    }

    private function filters(Request $request): array
    {
        $data = $request->validate([
            'search' => ['nullable', 'string', 'max:100'],
            'date_from' => ['nullable', 'date'],
            'date_to' => ['nullable', 'date', 'after_or_equal:date_from'],
            'company_id' => ['nullable', 'integer', 'exists:companies,id'],
            'plan_id' => ['nullable', 'integer', 'exists:subscription_plans,id'],
            'status' => ['nullable', 'string', Rule::in(self::ALL_STATUSES)],
            'period' => ['nullable', 'string', Rule::in(array_keys($this->periodOptions()))],
        ]);

        $period = $data['period'] ?? 'this_month';
        if ($period !== 'custom' && blank($data['date_from'] ?? null) && blank($data['date_to'] ?? null)) {
            [$data['date_from'], $data['date_to']] = $this->periodDates($period);
        }

        $data['period'] = $period;

        return $data;
    }

    private function filteredPaymentQuery(array $filters): Builder
    {
        return Payment::query()
            ->where('payment_type', 'subscription')
            ->when(filled($filters['search'] ?? null), function (Builder $query) use ($filters): void {
                $search = $filters['search'];
                $query->where(function (Builder $query) use ($search): void {
                    $query->where('transaction_reference', 'like', '%'.$search.'%')
                        ->orWhere('method', 'like', '%'.$search.'%')
                        ->orWhereHas('company', fn (Builder $company) => $company->where('name', 'like', '%'.$search.'%'));
                });
            })
            ->when(filled($filters['company_id'] ?? null), fn (Builder $query) => $query->where('company_id', $filters['company_id']))
            ->when(filled($filters['plan_id'] ?? null), fn (Builder $query) => $query->where('subscription_plan_id', $filters['plan_id']))
            ->when(filled($filters['status'] ?? null), fn (Builder $query) => $query->where('status', $filters['status']))
            ->when(filled($filters['date_from'] ?? null), fn (Builder $query) => $query->whereDate($this->revenueDateExpression(), '>=', $filters['date_from']))
            ->when(filled($filters['date_to'] ?? null), fn (Builder $query) => $query->whereDate($this->revenueDateExpression(), '<=', $filters['date_to']));
    }

    private function summary($payments, array $filters): array
    {
        $recognized = $payments->whereIn('status', self::RECOGNIZED_STATUSES);
        $companyCount = $recognized->pluck('company_id')->filter()->unique()->count();

        return [
            'total' => (float) $recognized->sum('amount'),
            'month' => (float) $recognized->filter(fn (Payment $payment) => $this->revenueDate($payment)?->isSameMonth(now()))->sum('amount'),
            'year' => (float) $recognized->filter(fn (Payment $payment) => $this->revenueDate($payment)?->isSameYear(now()))->sum('amount'),
            'pending' => (float) $payments->whereIn('status', self::PENDING_STATUSES)->sum('amount'),
            'verified_count' => $payments->whereIn('status', self::RECOGNIZED_STATUSES)->count(),
            'refunded_count' => $payments->where('status', 'refunded')->count(),
            'active_subscriptions' => Subscription::where('status', 'active')
                ->when(filled($filters['company_id'] ?? null), fn (Builder $query) => $query->where('company_id', $filters['company_id']))
                ->when(filled($filters['plan_id'] ?? null), fn (Builder $query) => $query->where('subscription_plan_id', $filters['plan_id']))
                ->count(),
            'average_company' => $companyCount > 0 ? (float) $recognized->sum('amount') / $companyCount : 0.0,
        ];
    }

    private function chartData($payments): array
    {
        $recognized = $payments->whereIn('status', self::RECOGNIZED_STATUSES);
        $months = collect(range(11, 0))->map(fn (int $offset) => now()->startOfMonth()->subMonths($offset));

        return [
            'monthlyLabels' => $months->map(fn (Carbon $month) => $month->format('M Y'))->values(),
            'monthlyValues' => $months->map(fn (Carbon $month) => (float) $recognized
                ->filter(fn (Payment $payment) => $this->revenueDate($payment)?->isSameMonth($month))
                ->sum('amount'))->values(),
            'planLabels' => $recognized->groupBy(fn (Payment $payment) => $payment->subscriptionPlan?->name ?? 'No plan')->keys()->values(),
            'planValues' => $recognized->groupBy(fn (Payment $payment) => $payment->subscriptionPlan?->name ?? 'No plan')->map(fn ($group) => (float) $group->sum('amount'))->values(),
            'statusLabels' => $payments->groupBy('status')->keys()->map(fn ($status) => str_replace('_', ' ', ucfirst($status)))->values(),
            'statusValues' => $payments->groupBy('status')->map->count()->values(),
            'companyLabels' => $recognized->groupBy(fn (Payment $payment) => $payment->company?->name ?? 'Unknown company')->map(fn ($group, $company) => $company)->values(),
            'companyValues' => $recognized->groupBy(fn (Payment $payment) => $payment->company?->name ?? 'Unknown company')->map(fn ($group) => (float) $group->sum('amount'))->values(),
        ];
    }

    private function exportRow(Payment $payment): array
    {
        return [
            $payment->transaction_reference ?? 'Payment #'.$payment->id,
            $payment->company?->name ?? '-',
            $payment->subscriptionPlan?->name ?? '-',
            $this->formatMoney((float) $payment->amount),
            str_replace('_', ' ', $payment->method),
            ucfirst(str_replace('_', ' ', $payment->status)),
            $this->revenueDate($payment)?->format('Y-m-d') ?? '-',
            $payment->verifier?->name ?? '-',
        ];
    }

    private function revenueDate(Payment $payment): ?Carbon
    {
        return $payment->verified_at ?? $payment->paid_at ?? $payment->created_at;
    }

    private function revenueDateExpression()
    {
        return DB::raw('COALESCE(verified_at, paid_at, created_at)');
    }

    private function currency(): string
    {
        return (string) SystemSetting::getValue('currency', 'USD');
    }

    private function formatMoney(float $amount): string
    {
        return $this->currency().' '.number_format($amount, 2);
    }

    private function periodOptions(): array
    {
        return [
            'today' => 'Today',
            'this_week' => 'This Week',
            'this_month' => 'This Month',
            'this_year' => 'This Year',
            'custom' => 'Custom Range',
        ];
    }

    private function periodDates(string $period): array
    {
        return match ($period) {
            'today' => [today()->toDateString(), today()->toDateString()],
            'this_week' => [now()->startOfWeek()->toDateString(), now()->endOfWeek()->toDateString()],
            'this_year' => [now()->startOfYear()->toDateString(), now()->endOfYear()->toDateString()],
            default => [now()->startOfMonth()->toDateString(), now()->endOfMonth()->toDateString()],
        };
    }

    private function activeFilters(array $filters): array
    {
        return collect($filters)
            ->filter(fn ($value) => filled($value))
            ->mapWithKeys(function ($value, string $key): array {
                $label = str_replace('_', ' ', ucfirst($key));

                if ($key === 'company_id') {
                    $value = Company::find($value)?->name ?? $value;
                }

                if ($key === 'plan_id') {
                    $value = SubscriptionPlan::find($value)?->name ?? $value;
                }

                if ($key === 'period') {
                    $value = $this->periodOptions()[$value] ?? $value;
                }

                return [$label => (string) $value];
            })
            ->all();
    }

    private function recordExportAudit(Request $request, string $type, array $filters): void
    {
        AuditLog::create([
            'company_id' => null,
            'user_id' => auth()->id(),
            'action' => 'revenue_export_'.$type,
            'module' => 'Revenue Overview',
            'auditable_type' => Payment::class,
            'auditable_id' => null,
            'description' => 'Exported Revenue Overview '.$type,
            'old_values' => null,
            'new_values' => ['filters' => $filters],
            'ip_address' => $request->ip(),
            'user_agent' => $request->userAgent(),
        ]);
    }

    private function safeCsvRow(iterable $row): array
    {
        return collect($row)
            ->map(function ($value): string {
                $value = (string) $value;

                return preg_match('/^[=+\-@]/', $value) ? "'".$value : $value;
            })
            ->all();
    }
}
