@extends('layouts.app')

@section('title', $projectRequest->title.' - Elevanix')

@section('content')
@include('partials.page-header', ['eyebrow' => 'Project Request', 'title' => $projectRequest->title, 'description' => $projectRequest->client?->name])
<div class="content-grid">
    <section class="content-card"><h2>Request Details</h2><dl class="detail-list mt-3"><dt>Status</dt><dd>@include('partials.status-badge', ['status' => $projectRequest->status])</dd><dt>Service</dt><dd>{{ $projectRequest->service_type ?? '-' }}</dd><dt>Budget</dt><dd>${{ number_format($projectRequest->estimated_budget ?? 0, 2) }}</dd><dt>Expected End</dt><dd>{{ $projectRequest->expected_end_date?->format('Y-m-d') ?? '-' }}</dd><dt>Description</dt><dd>{{ $projectRequest->description ?? '-' }}</dd><dt>Admin Note</dt><dd>{{ $projectRequest->admin_note ?? '-' }}</dd><dt>Rejection Reason</dt><dd>{{ $projectRequest->rejection_reason ?? '-' }}</dd></dl></section>
    <section class="content-card"><h2>Review</h2><form method="POST" action="{{ route('company-admin.project-requests.update', $projectRequest) }}">@csrf @method('PUT')<label class="form-label mt-3">Status</label><select class="form-select" name="status">@foreach(['draft','pending','under_review','approved','rejected','payment_requested','payment_confirmed','converted_to_project','cancelled'] as $status)<option value="{{ $status }}" @selected($projectRequest->status===$status)>{{ str_replace('_',' ',ucfirst($status)) }}</option>@endforeach</select><label class="form-label mt-3">Admin Note</label><textarea class="form-control" name="admin_note" rows="4">{{ old('admin_note', $projectRequest->admin_note) }}</textarea><button class="btn btn-primary mt-3" type="submit">Save review</button></form><div class="d-flex flex-wrap gap-2 mt-3"><form method="POST" action="{{ route('company-admin.project-requests.approve', $projectRequest) }}" data-confirm="Approve this request?">@csrf<button class="btn btn-outline-primary" type="submit">Approve</button></form><form method="POST" action="{{ route('company-admin.project-requests.convert', $projectRequest) }}" data-confirm="Convert this request into a project?">@csrf<button class="btn btn-outline-primary" type="submit">Convert</button></form></div><form class="mt-3" method="POST" action="{{ route('company-admin.project-requests.reject', $projectRequest) }}" data-confirm="Reject this request?">@csrf<label class="form-label">Rejection Reason</label><textarea class="form-control" name="rejection_reason" rows="3" required></textarea><button class="btn btn-outline-danger mt-2" type="submit">Reject request</button></form></section>
</div>
@endsection
