@extends('layouts.app')

@section('title', 'Audit Logs - Elevanix')

@section('content')
@include('partials.page-header', ['eyebrow' => 'Super Admin', 'title' => 'Audit Logs', 'description' => 'Search and filter important platform actions.'])
<section class="content-card">
    <form class="row g-3 mb-3" method="GET"><div class="col-md-3"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Search action or description"></div><div class="col-md-2"><select class="form-select" name="user"><option value="">All users</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected(request('user') == $user->id)>{{ $user->name }}</option>@endforeach</select></div><div class="col-md-2"><select class="form-select" name="company"><option value="">All companies</option>@foreach($companies as $company)<option value="{{ $company->id }}" @selected(request('company') == $company->id)>{{ $company->name }}</option>@endforeach</select></div><div class="col-md-2"><select class="form-select" name="module"><option value="">All modules</option>@foreach($modules as $module)<option value="{{ $module }}" @selected(request('module') === $module)>{{ $module }}</option>@endforeach</select></div><div class="col-md-1"><input class="form-control" type="date" name="from" value="{{ request('from') }}"></div><div class="col-md-1"><input class="form-control" type="date" name="to" value="{{ request('to') }}"></div><div class="col-md-1"><button class="btn btn-primary w-100" type="submit"><i class="fa-solid fa-filter"></i></button></div></form>
    <div class="table-responsive"><table class="table align-middle"><thead><tr><th>Action</th><th>Module</th><th>User</th><th>Company</th><th>Description</th><th>Date</th><th></th></tr></thead><tbody>@forelse($logs as $log)<tr><td>{{ str_replace('_', ' ', $log->action) }}</td><td>{{ $log->module ?? '-' }}</td><td>{{ $log->user?->name ?? 'System' }}</td><td>{{ $log->company?->name ?? '-' }}</td><td>{{ $log->description }}</td><td>{{ $log->created_at->format('M d, Y h:i A') }}</td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('super-admin.audit-logs.show', $log) }}"><i class="fa-regular fa-eye"></i> View</a></td></tr>@empty<tr><td colspan="7" class="empty-cell">@include('partials.empty-state', ['icon' => 'fa-clipboard-list', 'title' => 'No audit logs', 'message' => 'Tracked administrative actions will appear here.'])</td></tr>@endforelse</tbody></table></div>{{ $logs->links() }}
</section>
@endsection
