@extends('layouts.app')

@section('title', 'Payments and Revenue - Elevanix')

@section('content')
@include('partials.page-header', ['eyebrow' => 'Super Admin', 'title' => 'Payments and Revenue', 'description' => 'Track SaaS subscription revenue separately from client project payments.'])
<div class="stat-grid">@include('partials.stat-card', ['label' => 'Total Revenue', 'value' => '$'.number_format($totalRevenue, 2), 'icon' => 'fa-sack-dollar', 'tone' => 'green']) @include('partials.stat-card', ['label' => 'Monthly Revenue', 'value' => '$'.number_format($monthlyRevenue, 2), 'icon' => 'fa-chart-line']) @include('partials.stat-card', ['label' => 'Pending Payments', 'value' => '$'.number_format($pendingRevenue, 2), 'icon' => 'fa-clock', 'tone' => 'yellow'])</div>
<section class="content-card">
    <form class="row g-3 mb-3" method="GET"><div class="col-md-3"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Reference or company"></div><div class="col-md-3"><select class="form-select" name="company"><option value="">All companies</option>@foreach($companies as $company)<option value="{{ $company->id }}" @selected(request('company') == $company->id)>{{ $company->name }}</option>@endforeach</select></div><div class="col-md-2"><select class="form-select" name="plan"><option value="">All plans</option>@foreach($plans as $plan)<option value="{{ $plan->id }}" @selected(request('plan') == $plan->id)>{{ $plan->name }}</option>@endforeach</select></div><div class="col-md-2"><select class="form-select" name="status"><option value="">All statuses</option>@foreach($statuses as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ ucfirst($status) }}</option>@endforeach</select></div><div class="col-md-2"><button class="btn btn-primary w-100" type="submit"><i class="fa-solid fa-filter"></i> Filter</button></div></form>
    <div class="table-responsive"><table class="table align-middle"><thead><tr><th>Reference</th><th>Company</th><th>Plan</th><th>Amount</th><th>Method</th><th>Status</th><th>Date</th><th>Verified By</th><th></th></tr></thead><tbody>@forelse($payments as $payment)<tr><td>{{ $payment->transaction_reference ?? '#'.$payment->id }}</td><td>{{ $payment->company?->name }}</td><td>{{ $payment->subscriptionPlan?->name ?? '-' }}</td><td>${{ number_format($payment->amount, 2) }}</td><td>{{ str_replace('_', ' ', $payment->method) }}</td><td>@include('partials.status-badge', ['status' => $payment->status])</td><td>{{ $payment->paid_at?->format('M d, Y') ?? $payment->created_at->format('M d, Y') }}</td><td>{{ $payment->verifier?->name ?? '-' }}</td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('super-admin.payments.show', $payment) }}"><i class="fa-regular fa-eye"></i> View</a></td></tr>@empty<tr><td colspan="9" class="empty-cell">@include('partials.empty-state', ['icon' => 'fa-money-bill', 'title' => 'No payments found', 'message' => 'Subscription payments will appear here.'])</td></tr>@endforelse</tbody></table></div>{{ $payments->links() }}
</section>
@endsection
